controller_manager:
  ros__parameters:
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

      left_wheel_names: ["left_wheel_joint"]
      right_wheel_names: ["right_wheel_joint"]

      wheel_separation: 0.4
      wheel_radius: 0.05

      publish_rate: 50.0
      cmd_vel_timeout: 0.5
      use_stamped_vel: false

      odom_frame_id: odom
      base_frame_id: base_footprint
      enable_odom_tf: true

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      joints:
        - joint1
        - joint2
        - joint3
        - joint4

      state_publish_rate: 50
      command_publish_rate: 50
      constraints:
        goal_time: 0.5
        stopped_velocity_tolerance: 0.01
        joint1: { trajectory: 0.05, goal: 0.02 }
        joint2: { trajectory: 0.05, goal: 0.02 }
        joint3: { trajectory: 0.05, goal: 0.02 }
        joint4: { trajectory: 0.05, goal: 0.02 }
